import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Styles from "../page.module.css";
import Link from 'next/link';
import Head from 'next/head';
import { Suspense } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>

      <body>
        <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>
        </body>
    </html>
  );
}